graphql:
  server:
    url: http://localhost:4000

spring:
  application:
    name: administrate-graphql-client

logging:
  level:
    com.administrate.graphql: DEBUG
    org.springframework.graphql: DEBUG

